name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/ci
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  pipeline-ci:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: irango_order_test
          MYSQL_ROOT_HOST: '%'
      redis:
        image: redis:7.2.3
        ports:
          - 6379:6379
    steps:
      # Check out the source
      - name: Checkout Source
        uses: actions/checkout@v4
      # Setup node.js and cache
      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }} 
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      # Lint App
      - name: Lint App
        run: npm run lint:ci
      # Build App
      - name: Build App
        run: npm run build
      # Test Unit
      - name: Test
        run: npm test
      # Run Migration
      - name: Migration
        run: npm run migration:run
      # Test Integration
      - name: Test integration
        run: npm run test:integration --bail
      # Test bdd
      - name: Test Bdd
        run: npm run test:bdd

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      # - name: Notify CI process
      #   if: always()
      #   uses: appleboy/discord-action@master
      #   with:
      #     webhook_id: '${{ secrets.WEBHOOK_ID }}'
      #     webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
      #     message: CI of branch ${{ steps.extract_branch.outputs.branch }} executed ${{ job.status }}.